server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    data-password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
